### ISSUE TITLE
Unknown plugin "transform-runtime" when used with webpack

### ISSUE THREAD

**Issue by chrisg86** [vouill/vue-slideout#4] opened 2017-05-22 19:04 UTC
Hi,
I'm trying to use your plugin with webpack but I receive an error, when I import it like this in my app.js file:
```js
import Slideout from 'vue-slideout';
````

Error message:
```
ERROR in ./~/vue-slideout/lib/vue-slideout.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "myproject/node_modules/vue-slideout/.babelrc" at 0, attempted to resolve relative to "myproject/node_modules/vue-slideout"
    at myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (myproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (myproject/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (myproject/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (myproject/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (myproject/node_modules/babel-loader/lib/index.js:48:20)
    at Object.module.exports (myproject/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/app.js 15:19-42
 @ multi (webpack)-dev-server/client?http://localhost:9001 ./src/app.js
webpack: Failed to compile.
```

You might have to add your `.babelrc` file to `.npmignore`.

**Comment by vouill** [comment] 2017-05-22 22:35
Hey, thanks for reporting the issue. I will look into it tomorrow, does it work if you remove the `.babelrc` file from the lib folder? 
If not, can you try to run `npm install babel-plugin-transform-runtime` ?

Ill get back to you tomorrow !

**Comment by vouill** [comment] 2017-05-23 11:08
I did not manage to reproduce with webpack, can you tell more about your project setup ?

**Comment by chrisg86** [comment] 2017-05-23 18:47
Sorry for my late reply. It works if I manually remove the `.babelrc` file from your project root. 
Concerning my webpack config, I am loading my `js`files using babel-loader:

Extract from my webpack.config.js:

```
module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader'
      }
    ]
}
```

I'm using webpack v2.5.1. The babel versions I'm using:
```
"babel-core": "^6.24.1",
"babel-loader": "^7.0.0",
"babel-preset-es2015": "^6.24.1",
```

Anything else you require?

**Comment by vouill** [comment] 2017-05-31 18:47
I am sorry for the late reply, i got very busy recently.
Babel shouldnt transpile the node_module folder libraries. 

You need to change this : 
```
module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader'
      }
    ]
}
``` 


To this : 

``` 
module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
      }
    ]
}
``` 

It should do the trick !

Keep me updated :)

**Comment by vouill** [comment] 2017-06-06 16:35
Since there were no updates, i am closing this issue. If you face this issue again feel free to reopen it !

**Closed as completed by vouill** 2017-06-06 16:35 UTC

**Comment by chrisg86** [comment] 2017-06-08 18:19
Sorry for also being late. Your suggestion worked for me. Many thanks!

**Comment by vouill** [comment] 2017-06-08 20:34
Cheers 🎉
