### ISSUE TITLE
您好，使用您这个组件发现滑动太灵敏了，体验不是很好

### ISSUE THREAD

**Issue by algesthesiah** [vouill/vue-slideout#7] opened 2017-08-19 01:45 UTC
请问有解决办法么

**Comment by vouill** [comment] 2017-08-19 13:04
Well hello and thanks for opening an issue.
 Would it be possible to write it in english ? I am not sure about the google translate translation. 
Thanks !

**Comment by algesthesiah** [comment] 2017-08-21 09:03
Hello, use this component to find that slippery is too sensitive and experience is not very good。sorry,my English is bad

**Comment by vouill** [comment] 2017-08-23 11:25
would any of these options help you out ? https://github.com/Mango/slideout#api

**Comment by algesthesiah** [comment] 2017-08-23 11:28
options.tolerance？    Do you mean this api? I did not take effect

**Comment by vouill** [comment] 2017-08-23 11:53
Can you show me how did you set it ?

**Comment by vouill** [comment] 2017-08-23 11:55
Does the issue also occure in the demo? on which device size ? do you mean it can open / close too easily ?

**Comment by algesthesiah** [comment] 2017-08-23 12:23
I mean that you only set the slider around the slide is not set up and down on the slide to write on the slide if set to limit the sensitivity will not be so strong user experience is not click on the pop-up side

**Comment by algesthesiah** [comment] 2017-08-23 12:24
Please do a slide up and down restrictions, similar to the upper and lower sliding 20px will trigger the side of the pop

**Comment by vouill** [comment] 2017-08-23 13:25
Is the issue only on vue-slideout ? or can you reproduce it on slideout ? https://github.com/Mango/slideout ?

**Comment by algesthesiah** [comment] 2017-08-24 01:18
Slideout experience is very good, up and down the left side of the pop-up layer is not sensitive, vue-slideout experience is not very good, up and down the slide is easy to trigger the left pop

**Comment by vouill** [comment] 2017-08-31 19:15
Could you make a gif of your issue? if i get it right, its too easy to open the side menu when scrolling up and down. However i had no differences between slideout and vue-slideout. I am sorry we have so much trouble understand each other :(

**Comment by vouill** [comment] 2017-09-22 09:59
Closing this issue since i am sadly not sure what to fix. i would be glad to reopen if someone can help me translate !

**Closed as completed by vouill** 2017-09-22 09:59 UTC
