### ISSUE TITLE
Can't have more than one instance of a toggle-selector

### ISSUE THREAD

**Issue by jackmcdade** [vouill/vue-slideout#8] opened 2017-08-30 18:46 UTC
If i have more than one of any class defined in `:toggle-selectors`, either all of them don't work, or only one of them works at a time.

**Comment by vouill** [comment] 2017-08-31 19:11
Hello, thanks for opening an issue :)

So i checked, i had no issue with multiple toggle selectors, can you be  more precise ? 

Do you mind reproducing your issue ?
https://codesandbox.io/s/k3q1zjjml5

**Comment by jezmck** [comment] 2017-09-15 13:31
That codesandbox link shows an error:

> TypeError
window.dll_bundle is not a function

**Comment by vouill** [comment] 2017-09-15 13:45
Indeed, i am investigating it, thanks for the report !

**Comment by vouill** [comment] 2017-09-15 13:59
Should be working now. I just updated the vue package in codesandbox. might break at each new vue release, i'll try to keep an eye on it :)

**Comment by vouill** [comment] 2017-09-22 09:52
I am closing this issue since there were no updates

**Closed as completed** 2017-09-22 09:52 UTC
